### ISSUE TITLE
npm not up to date

### ISSUE THREAD

**Issue by narf** [treygriffith/connect-mongodb#1]
The npm version seem a bit old, is it planned to refresh it?

**Comment by masylum** [comment]
Now the latest version is on npm.
Thanks for your feedback!

**Comment by narf** [comment]
nice, keep the good work coming

**Comment by narf** [comment]
Hum, it seems that the module isn't installed properly i tried on two different computer and i can't require the module.
Nothing is in the path of installed node modules can you check this?

**Comment by masylum** [comment]
mm.. this is so embarrassing! Try now. I tried locally and it worked fine! I missed a param on the package.json...

**Comment by narf** [comment]
Don't seem to work either. I gave npm a custom repertory for my nodes modules, maybe that's the problem. 
It appears that npm download the files properly (all sources are in the source repertory) but the module is not installed properly (can't require it) because npm has not put the module in the module repertory (Where all the modules are installed, there is no connect-mongodb)

**Comment by masylum** [comment]
I just installed it on a fresh and clean machine and it worked properly.
Try to:
    npm uninstall connect-mongodb
    npm install connect-mongodb

And then paste here:
    npm ls installed
    ls /usr/local/lib/node/ OR your custom folder

**Comment by narf** [comment]
> :~$ npm ls installed
> npm info it worked if it ends with ok
> npm info using npm@0.2.3-6
> cloud9@0.1.2                             =fjakobs =mikedeboer active installed latest remote
> connect@0.2.7                            =creationix =tjholowaychuk active installed latest remote
> connect-auth@0.1.3                       =ciaranj active installed latest remote
> connect-mongodb@0.0.2                    =masylum active installed latest remote
> couchdb@1.0.0                            =nathan active installed latest remote
> express@1.0.0rc4                         =tjholowaychuk active installed latest remote
> eyes@0.1.6                               =cloudhead active installed latest stable remote
> geddy@0.1.3                              =mde active installed latest remote
> jake@0.1.6                               =mde active installed latest remote
> mongodb@0.7.9                            =christkv active installed latest stable remote
> npm@0.2.3-6                              =isaacs active installed remote
> oauth@0.8.2                              =ciaranj active installed latest remote
> vows@0.5.1                               =cloudhead active installed remote
> npm ok

And the ls:

> cloud9         connect-auth        express           jake           npm          vows
> cloud9@0.1.2   connect-auth@0.1.3  express@1.0.0rc4  jake@0.1.6     npm@0.2.3-6  vows@0.5.1
> connect        couchdb             eyes              mongodb        oauth        wafadmin
> connect@0.2.7  couchdb@1.0.0       eyes@0.1.6        mongodb@0.7.9  oauth@0.8.2

Sorry for the ugly formatting.

**Comment by masylum** [comment]
OMG... I don't get it!
I don't know what's wrong with my package.json
You can git clone while I discover what's wrong.
