### ISSUE TITLE
Session#touch

### ISSUE THREAD

**Issue by jeromegn** [treygriffith/connect-mongodb#10]
As documented here:
http://senchalabs.github.com/connect/middleware-session.html

Is it possible it's not working with your session store? I'm not sure if it's me or the library here though...

I'm trying to keep the session alive as long as the websocket connection is alive... so I'd like to `touch` the session everytime I receive a message or send one with socket.io.

To gather the session within socket.io, I take the request's session and fetch it with your session store. Once I got it, I tried to `touch` it, I got an undefined method...

Am I using the right object here? Appreciate any help on the matter! Thanks.

**Comment by masylum** [comment]
touch is a method implemented on connect https://github.com/senchalabs/connect/blob/master/lib/middleware/session/session.js#L43

For using you have to do `req.session.touch`.

Shouldn't be problematic because touch doesn't interact with the store.
