### ISSUE TITLE
After upgrading to Express 2.3.2 receiving error

### ISSUE THREAD

**Issue by scottwoodall** [treygriffith/connect-mongodb#14]
After I upgraded to Express to 2.3.2 (which also upgrades Connect to 1.4.0) I am now receiving an error when trying to use connect-mongodb for my session store. If I switch back to Express 2.2.2 I don't have any issues:

TypeError: Object #<Store> has no method 'createSession'
    at /usr/local/lib/node/.npm/connect/1.4.0/package/lib/middleware/session.js:324:15
    at /usr/local/lib/node/.npm/connect-mongodb/0.2.2/package/lib/connect-mongodb.js:136:11
    at [object Object].<anonymous> (/usr/local/lib/node/.npm/mongodb/0.9.2/package/lib/mongodb/collection.js:448:35)
    at [object Object].emit (events.js:67:17)
    at [object Object].<anonymous> (/usr/local/lib/node/.npm/mongodb/0.9.2/package/lib/mongodb/db.js:90:12)
    at [object Object].emit (events.js:64:17)
    at Socket.<anonymous> (/usr/local/lib/node/.npm/mongodb/0.9.2/package/lib/mongodb/connection.js:82:16)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:665:31)
    at IOWatcher.onReadable [as callback](net.js:177:10)

My app.js looks like this:

var mongoStore = require('connect-mongodb');
app.set('db-uri', 'mongodb://localhost/questions');
app.configure(function(){
  app.set('views', __dirname + '/views');
  app.set('view engine', 'jade');
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(express.cookieParser());
  app.use(express.session({
    secret: 'hi',
    store: new mongoStore({url: app.set('db-uri')})
  }));
  app.use(express.logger({ format: '\x1b[1m:method\x1b[0m \x1b[33m:url\x1b[0m :response-time ms' }))
  app.use(app.router)
  app.use(express.static(__dirname + '/public'));
});

**Comment by masylum** [comment]
Apparently is something to do with https://github.com/senchalabs/connect/issues/268

I will try to push a 1.4 compatible version tonight.

**Comment by storypixel** [comment]
Having a similar issue, thx for pushing later tonight

**Comment by masylum** [comment]
Try now. `npm update connect-mongodb`. 0.3.0 should work.
New store relies on inheritance and I was not doing it properly. As a side effect of this, now you have to create the stores with the `new` operator.

**Comment by scottwoodall** [comment]
Working for me. Thank you for the quick fix/response.

**Comment by storypixel** [comment]
You rock man thx
