### ISSUE TITLE
How to clean up the database?

### ISSUE THREAD

**Issue by applemate** [treygriffith/connect-mongodb#15]
Hi, I can see that in every visits, there will be a new record stored in the database, would those records delete itself or I have to do it? If I have to do it, how could I?

**Comment by masylum** [comment]
You have to set up the maxAge directive.

```
connect.session({
    cookie: {maxAge: 60000 * 20}, // 20 minutes
    secret: 'foo'
});
```

Every minute (by default) connect-mongodb cleans all the expired sessions.

https://github.com/masylum/connect-mongodb/blob/master/lib/connect-mongodb.js#L98
