### ISSUE TITLE
can not call method foreach of undefined

### ISSUE THREAD

**Issue by applemate** [treygriffith/connect-mongodb#18]
this happens periodically every 10-20 minutes. The errors:
<code>
/usr/local/lib/node/.npm/mongodb/0.9.3/package/lib/mongodb/db.js:624
  dbcopy.serverConfig.servers.forEach(function(server) {
                              ^
TypeError: Cannot call method 'forEach' of undefined
    at [object Object].checkMaster_ (/usr/local/lib/node/.npm/mongodb/0.9.3/package/lib/mongodb/db.js:624:31)
    at [object Object].executeCommand (/usr/local/lib/node/.npm/mongodb/0.9.3/package/lib/mongodb/db.js:569:12)
    at [object Object].findOne (/usr/local/lib/node/.npm/mongodb/0.9.3/package/lib/mongodb/collection.js:456:11)
    at MongoStore.get (/usr/local/lib/node/.npm/connect-mongodb/0.3.0/package/lib/connect-mongodb.js:130:15)
    at [object Object].<anonymous> (/var/www/html/nodejs/server.js:69:15)
    at [object Object].emit (events.js:64:17)
    at [object Object]._onMessage (/usr/local/lib/node/.npm/socket.io/0.6.17/package/lib/socket.io/client.js:58:10)
    at Parser.<anonymous> (native)
    at Parser.emit (events.js:64:17)
    at Parser.parse (/usr/local/lib/node/.npm/socket.io/0.6.17/package/lib/socket.io/transports/websocket.js:195:12)
[root@localhost nodejs]# 
</code>

This issue will crash mongoDB and nodejs server at the same time. below is the code, that the error might be talking about

<pre>
socket.on('connection', function(client) {
    client.on('message', function(message) {
        //line69 is here
        mongo_store.get(message.chatSessionId, function(err, session) {
            //console.log(message.chatSessionId);
            console.log(message.text);
            //console.log(session);
            if (err || !session) {
                client.send('Your chat session has been expired. Try reload the page');
                return;
            }
            else if(message.username === session.username){             
                socket.broadcast(message.username+': '+ wordFilter(message.text));
            }
        });
    });
});
</pre>

**Comment by masylum** [comment]
can you paste your mongo_store configuration?

**Comment by applemate** [comment]
I'd love you, Where can I get my mongo_store configuration ?

**Comment by applemate** [comment]
is this it ?

<pre>var mongo_store = new mongoStore(),
express = require('express');

app.use(express.bodyParser());
app.use(express.cookieParser());
app.use(express.session({ 
    secret: 'something', 
    store: mongo_store, 
    cookie: {
        maxAge: 2592000 //30 days
    }
}));

socket.on('connection', function(client) {
    client.on('message', function(message) {        
        mongo_store.get(message.chatSessionId, function(err, session) {
            //console.log(message.chatSessionId);
            console.log(message.text);
            //console.log(session);
            if (err || !session) {
                client.send('Your chat session has been expired. Try reload the page');
                return;
            }
            else if(message.username === session.username){             
                socket.broadcast(message.username+': '+ wordFilter(message.text));
            }
        });
    });
});
</pre>


That's all the code I have about connect-mongo in my chat app

**Comment by masylum** [comment]
update the driver and the module `npm update mongodb` and `npm update connect-mongodb`. Let me know if still happens.

**Comment by applemate** [comment]
remove all the database, update mongodb and update connect-mongodb will solve the problem. I also changed the mongoStore configure code to exactly like yours.
