### ISSUE TITLE
why there are two expires

### ISSUE THREAD

**Issue by applemate** [treygriffith/connect-mongodb#20]
<pre>{ "_id" : "na11Ioshb86v5nKRl7WMlVzn.TZypW4Zn6IWUQQ8tUK0k73H3VWqCXhzTq5wii+ssue4", 
"session" : "{\"lastAccess\":1306946645365,\
"cookie\":{\"originalMaxAge\":2592000,\"expires\":\"2011-06-01T17:27:17.369Z\",\"httpOnly\":true,\"path\":\"/\"},\"username\":\"forestgumb\"}", 
"expires" : NumberLong("1306949237000") }</pre>

That's a record in collection sessions in database chat. You can see there are two expires, the first expries is "2011-06-01T17:27:17.369Z", 30 days from this date, which is exactly what I set in mongo_store configure. The second one is 1306949237000, which is 15-Jul-2010 2: 30pm, only 15 days from this date.

which one of those expires determine the expiration of the session in database ?

**Comment by masylum** [comment]
The second one should be the same but parsed:
https://github.com/masylum/connect-mongodb/blob/master/lib/connect-mongodb.js#L186

Every `reapInterval` the parsed expires is checked in order to delete expired sessions:
https://github.com/masylum/connect-mongodb/blob/master/lib/connect-mongodb.js#L127

I could parse directly the session expires, but it could break some code.

**Comment by applemate** [comment]
Sorry but they aren't the same, my point is if the first one is 30 days, the second only 15 days.

You see the first one 2011-06-01 which is 30 days from now.

when I convert the second one to date it will be 2010-Jul-15, the date is wrong and the year is also wrong.

**Comment by masylum** [comment]
(new Date(1306949237000)).toString() => "Wed Jun 01 2011 19:27:17 GMT+0200 (CEST)"

The source code speaks for itself:

```
var update = {_id: sid, session: sess};
if (sess && sess.cookie && sess.cookie.expires) {
  update.expires = Date.parse(sess.cookie.expires);
}
_collection.update({_id: sid}, update, {upsert: true}, function ....
```

BTW, there is a new version without the session being stringified :) `npm connect-mongodb update`

**Comment by applemate** [comment]
is the latest version 0.1.2?

**Comment by masylum** [comment]
0.4.0 :)

https://github.com/masylum/connect-mongodb/blob/master/package.json

**Comment by applemate** [comment]
I do npm update connect-mongo, it say there's nothing to update. Perhaps, there is a problem with npm itself ?

**Comment by applemate** [comment]
oh well i was doing npm install connect-mongo the whole time. there should be "db" suffix. :)

**Comment by applemate** [comment]
ok now I have 0.4 I believe can make my point clearer. Please check the expires, they are completely different

<pre>{ "_id" : "ddJQkbF7WlW077cOuTRQurza.3q6VjwXI4hQOJT4jy2KmR7qeHG/Lz2rV20qNJIwFZsM",
 "session" : { "lastAccess" : NumberLong("1306973677411"), 
"cookie" : { "path" : "/", "httpOnly" : true, "_expires" : ISODate("2011-06-02T00:57:49.416Z"), "originalMaxAge" : 2592000 }, "username" : "forestgumb" }, "expires" : NumberLong("1306976269000") }</pre>


306976269000 isn't 2011-06-02

**Comment by masylum** [comment]
(new Date(1306976269000)).toString() => "Thu Jun 02 2011 02:57:49 GMT+0200 (CEST)"

So, your user is called 'forestgumb'

**Comment by applemate** [comment]
<?php echo date('Y-M-d', 1306976269000) ?> => "2011-May-24"

yeah forest is the admin :)

**Comment by applemate** [comment]
I keep insisting because mongo keeps atuo-deleting the session after 1 hour, not 30 days. That's driving me nut.

**Comment by masylum** [comment]
I don't know, just fork the project and place console.logs to see what's going on.

This module does very little, and for the expires, as I told you before, it just uses `Date.parse`.
I don't know how php date works, but it doesn't matter because all the date comparisions happen on the js side.

Get dirty with the module because and if you find something, pull request.

**Comment by applemate** [comment]
now I know, the set cookie maxage should be put in miliseconds not second, So I should've put 60_60_24_30_1000, for 30 days.

Another thing, mongo runs side in side with node ( in the same server) is a crashing magnet. when turn mongo on, my system crashes every hours. I think I need to set up a dedicated server for mongo, what do think?

**Comment by masylum** [comment]
is always better to isolate services, although, check why it crashes and try to fix it.
