### ISSUE TITLE
given _id

### ISSUE THREAD

**Issue by Philmod** [treygriffith/connect-mongodb#21]
Hi,

Is it possible to (re)generate a session with a _id given?

Thanks,
Philippe

**Comment by masylum** [comment]
I guess you can implement your own regenerate by calling `connect-mongodb#destroy` method and then `session#generate`

https://github.com/masylum/connect-mongodb/blob/master/lib/connect-mongodb.js#L204
https://github.com/senchalabs/connect/blob/master/lib/middleware/session.js#L230

**Comment by Philmod** [comment]
Thanks for replying!

I'm ok with the 'connect-mongodb#destroy' by calling : 'req.session.destroy(
function(err) {} )', but how I call the 'session#generate' with the given
_id??

Philippe

2011/6/7 masylum <
reply@reply.github.com>

**Comment by masylum** [comment]
`generate` accepts a request, and it creates his own _id.
I recommend you to add some `console.log` and trace what the session middleware is doing at each point as its not easy to follow.

**Comment by Philmod** [comment]
So if I want my own _id, I cannot use 'session#generate'?

2011/6/7 masylum <
reply@reply.github.com>

**Comment by masylum** [comment]
No, you will have to hack your own solution for that.

**Comment by Philmod** [comment]
Ok, thank you!

The model of 'Session' in mongodb changed, right?  Because I'm using
mongoose to add some attributes to the session entry, and it's different
with the last versions of connect(-mongodb).

2011/6/7 masylum <
reply@reply.github.com>

**Comment by masylum** [comment]
yes, update with npm and remove the old sessions. Now we can store the data as a document where before was a string with the json serialized.

**Comment by Philmod** [comment]
So the new schema is :
{
  _id: , session: , expires:
}
And the datas are in 'session'?

2011/6/7 masylum <
reply@reply.github.com>

**Comment by masylum** [comment]
{_id:, data:{}, expires:}

**Comment by masylum** [comment]
sorry, {_id:, session: {}, expires:}

https://github.com/masylum/connect-mongodb/blob/master/lib/connect-mongodb.js#L181

Check the source. Is very little.
