### ISSUE TITLE
search monge_store using value different from sessionId

### ISSUE THREAD

**Issue by applemate** [treygriffith/connect-mongodb#22]
I store usernames in the mongo_store, and I want to retrieve session using username instead of sessionId, look like it doesn't work that way?

My data scheme:

<pre>{ lastAccess: { low_: 1896901905, high_: 304 },
  cookie: 
   { path: '/',
     httpOnly: true,
     _expires: Fri, 08 Jul 2011 21:02:44 GMT,
     originalMaxAge: { low_: -1702967296, high_: 0 } },
  ioid: '8401068514212966',
  channel: 'all',
  username: 'xuka' }</pre>
 

nodejs code

```
    <pre>mongo_store.get(SessionId, function(err, session) {
        //results
    });

    mongo_store.get(username, function(err, session) {
        //no result
    });</pre>
```

**Comment by masylum** [comment]
please check the source before asking!

https://github.com/masylum/connect-mongodb/blob/master/lib/connect-mongodb.js#L158

It always asks for _id. If you want to do a different query, use the mongo driver directly.
