### ISSUE TITLE
Not compatible with node v0.5.1-pre

### ISSUE THREAD

**Issue by mockee** [treygriffith/connect-mongodb#32]
$ npm install connect-mongodb

> npm ERR! Unsupported
> npm ERR! Not compatible with your version of node/npm: connect@1.5.1
> npm ERR! Required: {"node":">= 0.4.1 < 0.5.0"}
> npm ERR! Actual:   {"npm":"1.0.18","node":"v0.5.1-pre"}

**Comment by masylum** [comment]
Can you clone it and try it?, if it works pull request updating the package.json thanks.
