### ISSUE TITLE
Database Connection URI Support

### ISSUE THREAD

**Issue by alexyoung** [treygriffith/connect-mongodb#4]
Can you make connect-mongodb support database connection URIs like mongoose?

It'll simplify configuration for apps that use mongoose already.

**Comment by masylum** [comment]
Added optional url (so you can reuse it from mongoose) closed by b59694548936741b0c4041ceb1f4533ca7b58a44

**Comment by alexyoung** [comment]
Excellent

**Comment by jgallen23** [comment]
is this fix in the npm version?  this doesn't seem to be working for me
