### ISSUE TITLE
Seems to be broken with mongodb client 0.9.7

### ISSUE THREAD

**Issue by cryptix** [treygriffith/connect-mongodb#42]
With a quite basic/default setup i get this appon the first connection.
can somebody verify?

```
/home/cryptix/node_modules/connect-mongodb/lib/connect-mongodb.js:81
      _collection.remove({expires: {'$lte': Date.now()}}, function () { });
                  ^
TypeError: Cannot call method 'remove' of null
    at Timer.<anonymous> (/home/cryptix/node_modules/connect-mongodb/lib/connect-mongodb.js:81:19)
    at Timer.ontimeout (timers.js:203:14)
```

**Comment by benbuckman** [comment]
I'm having the same problem. It's inconsistent but frequent, on app load. Must be some async race condition going on. Please re-open and review, thanks!

**Comment by bunkat** [comment]
I'm seeing this as well with Node v0.6.12 and connect-mongodb 1.1.3.

**Comment by dmauro** [comment]
I just upgraded from Node v0.6 to v0.8.1 and started seeing this. Would love a solution for this.
