### ISSUE TITLE
Why is the session stringified?

### ISSUE THREAD

**Issue by niftylettuce** [treygriffith/connect-mongodb#47]
https://github.com/masylum/connect-mongodb/blob/master/lib/connect-mongodb.js#L140

this prevents us using Mongoose to recreate the db schema, and then try a query like this...

``` bash
db.model('Sessions').find({"session._csrf":"boiajwofijaweifj"});
```

^ won't work since the data in DB is a string vs JSON

**Comment by masylum** [comment]
https://github.com/masylum/connect-mongodb/pull/36
