### ISSUE TITLE
Problem with connecting to hosted services like mongolabs / mongohq

### ISSUE THREAD

**Issue by aemsley** [treygriffith/connect-mongodb#5]
Following this tutorial
http://dailyjs.com/2010/12/06/node-tutorial-5/

Using the session store with a hosted db solution like those mentioned in the title seems to break something. Works great with a fresh local mongodb tho...

Any ideas?

**Comment by masylum** [comment]
This module uses the native driver `MongoDB.connect(url, callback)`.
You can pass the url directly or build it passing the parameters.

https://github.com/masylum/connect-mongodb/blob/master/lib/connect-mongodb.js#L52-53

**Comment by aemsley** [comment]
To reproduce this error, checkout the commit listed at the bottom of the blog post, npm the dependencies and then change the mongo uri to a hosted one.

After some more debugging I have found where things hang.

It seems to take fairly long to initially connect to the database, but it does appear to do it.

Once a request to the server comes in, it hangs at

/usr/local/lib/node/.npm/mongodb/0.7.9/package/lib/mongodb/connection.js:105:21

with: Error: EPIPE, Broken pipe

again, this is not an issue with mongoose which connects instantly and writes completely fine to the hosted db.

Have you had a chance to check this out?

**Comment by masylum** [comment]
Fixed compatibility with 0.7.9 driver. closed by 2351bc84a0213d32a8450a92d51559dc4d1bec4e

**Comment by masylum** [comment]
I just pushed a commit that should fix this. 
I saw several problems using the mongodb driver 0.7.9, the url parser somehow was not handling the authentication correctly. I checked how the mongoose guys are doing this and they are parsing the url by themselves instead of relying on the driver for that.

Please try it again now. It works perfectly in my machine using node 0.2.4 and mongohq.

**Comment by aemsley** [comment]
Hello,

Thank you so much for looking into this. Everything works great now.

Cheers!
