### ISSUE TITLE
dependencies to mongodb 0.9.7 build failed on Win32 platform

### ISSUE THREAD

**Issue by lyhcode** [treygriffith/connect-mongodb#51]
mongodb 0.9.7 dependency break the "npm install connect-mongodb" installation on win32 platform.
newer mongodb like 1.0.2 will fix this problem
thanks

npm ERR! error rolling back connect-mongodb@1.1.3 Error: ENOTEMPTY, rmdir 'C:\AC
AD_TAJ\node_modules\connect-mongodb'

npm ERR! Unsupported
npm ERR! Not compatible with your operating system or architecture: mongodb@0.9.7
npm ERR! Valid OS:    linux,darwin,freebsd
npm ERR! Valid Arch:  any
npm ERR! Actual OS:   win32
npm ERR! Actual Arch: ia32
npm ERR!
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd C:\ACAD_TAJ
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.21
npm ERR! code EBADPLATFORM
npm ERR! message Unsupported
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\ACAD_TAJ\npm-debug.log
npm not ok

**Comment by cortfr** [comment]
+1

**Comment by masylum** [comment]
new version has the dependencies up to date
