### ISSUE TITLE
Plans for 0.7.x/0.8.x branch?

### ISSUE THREAD

**Issue by zzen** [treygriffith/connect-mongodb#54]
The dependencies included (mongodb and connect) are both too old for the 0.8 branch. Any plans on making this 0.8-compliant?

**Comment by Raynos** [comment]
+1 for 0.8 support

**Comment by lancejpollard** [comment]
+1

It's not working on 0.8.0 because connect is set to version 1.8.5, and connect@1.8.5 is hardcoded to node <= 0.7.0. If you can change the connect version to `>= 1.8.5`, that would help.

**Comment by tleach** [comment]
+1 for 0.8 please!

**Comment by lancejpollard** [comment]
I just changed this one line and it's working fine on Node 0.8.0 (even works great on Heroku):

https://github.com/viatropos/connect-mongodb/blob/master/package.json#L8

**Comment by Raynos** [comment]
@viatropos https://github.com/masylum/connect-mongodb/pull/56 ;)

**Comment by masylum** [comment]
new version has the dependencies up to date
