### ISSUE TITLE
no method get?

### ISSUE THREAD

**Issue by tglines** [treygriffith/connect-mongodb#6]
I get this long error out of my app that follows your example pretty closely.  (running node v0.2.5)

https://gist.github.com/779266

<script src="https://gist.github.com/779266.js?file=connect-mongodb_error"></script>

**Comment by masylum** [comment]
Can you please paste here how do you initialize the mongoStore?

It should be something like this:

```
connect.session({store: mongoStore({
  dbname: 'production',
  username: 'foo',
  password: 'bar'
})})
```

And it looks like you just pass:

```
connect.session({store: mongoStore});
```

**Comment by tglines** [comment]
Ahh alright, I'm testing out an unsecured mongodb server and thats exactly what I did.  I'll secure it and connect to it with username and password.  Thanks so much for the help.

**Comment by masylum** [comment]
You can use an unsecured one. You can even pass your connection string.

```
connect.session({store: mongoStore('http://foo:bar@hostname.com:2718')});
```
