### ISSUE TITLE
reapInterval or how to reap stale sessions

### ISSUE THREAD

**Issue by akunz** [treygriffith/connect-mongodb#7]
Hello,

is there a option delete stale sessions in mongodb? I set maxAge but stale sessions are still in my mongodb.

Thanks for your help.

**Comment by masylum** [comment]
Added reapInterval to remove expired sessions. Works with latest connect. closed by 6dffe5b03b76432bceacce349532bdbfd2a5e240 and closed by 6dffe5b03b76432bceacce349532bdbfd2a5e240

**Comment by akunz** [comment]
Thanks so much.
