### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by airandfingers** [treygriffith/connect-mongodb#71]
Is connect-mongodb licensed? If so, under what license? I need to provide this information for any and all npm modules I use.

**Comment by masylum** [comment]
It's not licensed, I'm barely maintaining it :(

**Comment by dvv** [comment]
please, feel free to choose any you like

**Comment by m0rganic** [comment]
@airandfingers @dvv 
The maintainer of this project is not obligated to choose an open source license.. however if there is no license for the project it is still technically owned by the original author under standard copyright law. 

Dear maintainer, 
Please consider an open source license it if you want to share it with the community. The MIT license is really straight forward and very "share" friendly.

Github recently released this site to help clear up confusion around licensing - http://choosealicense.com/. See the link at the bottom "What if I don't want to choose a license? You don't have to."
